# Generates BarLayout.qml — the plugin instantiation layer for kh-bar.
#
# Parameters:
#   leftPlugins   — list of QML type names (strings) for the left Row
#   rightPlugins  — list of QML type names (strings) for the right Row
#
# All plugin types must be present in $out/ when the bar is built (i.e. the
# corresponding .qml files are placed alongside shell.qml by barConfig).
# User-supplied plugins land there via the extraPluginDirs mechanism.
#
# Plugins do NOT receive cfg as a property — they import NixConfig directly
# since it is co-located in $out/ and auto-discovered by Quickshell.
#
# Usage:
#   import ./bar-layout.nix {
#     inherit pkgs lib;
#     leftPlugins  = [ "Workspaces" ];
#     rightPlugins = [ "Clock" ];
#   }
# Each plugin entry is { name, src } where src is the path to the .qml file.
# name is the component name (e.g. "Clock"), src is e.g. ./qml/bar/Clock.qml.
{ pkgs
, lib
, leftPlugins  ? []
, rightPlugins ? []
}:
let
  leftResolved  = leftPlugins;
  rightResolved = rightPlugins;

  # Extract the plugin body from a .qml file: strip comments, imports, and the
  # outer type wrapper (first non-blank/comment line) plus its closing brace.
  pluginBody = { name, src }:
    let
      raw = builtins.readFile src;
      lines = lib.splitString "\n" raw;
      bodyLines = lib.filter
        (l: !(lib.hasPrefix "//" l) && !(lib.hasPrefix "import " l) && l != "")
        lines;
      inner = lib.concatStringsSep "\n        "
        (lib.init (builtins.tail bodyLines));
      # Rename all QML ids to plugin-scoped names to avoid "id is not unique"
      # errors when multiple plugins are inlined into the same QML file.
      # Covers every id used across the built-in plugins; user plugins that
      # introduce new ids must avoid clashing with other plugins' ids.
      suffix = "_${name}";
      uniqueInner = builtins.replaceStrings
        [ "id: cfg"   "cfg."
          "id: row"   "row."
          "id: label" "label."
        ]
        [ "id: cfg${suffix}"   "cfg${suffix}."
          "id: row${suffix}"   "row${suffix}."
          "id: label${suffix}" "label${suffix}."
        ]
        inner;
    in uniqueInner;

  # Render a plugin as an anonymous Item inline in a Row.
  # barHeight is exposed as a local property bound to layout.barHeight.
  mkInlineItem = p:
    ''
            // ── ${p.name} ──
            Item {
                property int barHeight: layout.barHeight
                implicitHeight: barHeight
                width: implicitWidth
                height: implicitHeight
                ${pluginBody p}
            }
    '';

  mkSlot = plugins:
    lib.concatMapStrings mkInlineItem plugins;

  leftItems  = mkSlot leftResolved;
  rightItems = mkSlot rightResolved;
in
pkgs.writeText "BarLayout.qml" ''
  // Generated by bar-layout.nix — do not edit by hand.
  // Configure plugins via the bar-layout.nix arguments or the hm-module options.
  import QtQuick
  import Quickshell.Hyprland
  import Quickshell.Services.Pipewire
  import Quickshell.Services.Mpris

  Item {
      id: layout
      required property int barHeight

      // ── Left plugins ───────────────────────────────────────────────────────
      Row {
          anchors.left: parent.left
          anchors.leftMargin: 8
          anchors.verticalCenter: parent.verticalCenter
          spacing: 4

  ${leftItems}    }

      // ── Right plugins ──────────────────────────────────────────────────────
      Row {
          anchors.right: parent.right
          anchors.rightMargin: 8
          anchors.verticalCenter: parent.verticalCenter
          layoutDirection: Qt.RightToLeft
          spacing: 4

  ${rightItems}    }
  }
''
