# config.nix — Nix → QML theme boundary.
# Generates NixConfig.qml: exposes Stylix colors and font settings.
{
  pkgs,
  colors,
  fontName,
  fontSize,
  volumeMax ? 1.5,
}:
pkgs.writeText "NixConfig.qml" ''
  // Build-time theme configuration generated by config.nix.
  import QtQuick

  QtObject {
      readonly property string fontFamily: "${fontName}"
      readonly property int    fontSize:   ${toString fontSize}
      readonly property real   volumeMax:  ${toString volumeMax}

      readonly property QtObject color: QtObject {
          readonly property string base00: "#${colors.base00}"
          readonly property string base01: "#${colors.base01}"
          readonly property string base02: "#${colors.base02}"
          readonly property string base03: "#${colors.base03}"
          readonly property string base04: "#${colors.base04}"
          readonly property string base05: "#${colors.base05}"
          readonly property string base06: "#${colors.base06}"
          readonly property string base07: "#${colors.base07}"
          readonly property string base08: "#${colors.base08}"
          readonly property string base09: "#${colors.base09}"
          readonly property string base0A: "#${colors.base0A}"
          readonly property string base0B: "#${colors.base0B}"
          readonly property string base0C: "#${colors.base0C}"
          readonly property string base0D: "#${colors.base0D}"
          readonly property string base0E: "#${colors.base0E}"
          readonly property string base0F: "#${colors.base0F}"
      }
  }
''
