# ffi.nix — Nix → QML FFI boundary.
# Generates NixBins.qml: exposes store-path binaries as QML properties.
{
  pkgs,
  lib,
  extraBins ? { },
}:
pkgs.writeText "NixBins.qml" ''
  // Build-time FFI generated by ffi.nix.
  import QtQuick

  QtObject {
      readonly property string bash:     "${lib.getExe' pkgs.bash "bash"}"
      readonly property string cliphist: "${lib.getExe pkgs.cliphist}"
      readonly property string hyprctl:  "${lib.getExe' pkgs.hyprland "hyprctl"}"
      readonly property string jq:       "${lib.getExe pkgs.jq}"
      readonly property string kitty:    "${lib.getExe pkgs.kitty}"
      readonly property string stat:     "${lib.getExe' pkgs.coreutils "stat"}"
      readonly property string wlCopy:   "${lib.getExe' pkgs.wl-clipboard "wl-copy"}"
      ${lib.concatStringsSep "\n      "
        (lib.mapAttrsToList (name: val: ''readonly property string ${name}: "${val}"'') extraBins)}
  }
''
