# ffi.nix — Nix → QML FFI boundary.
# Generates NixConfig.qml: exposes Stylix colors, font settings, and
# store-path binaries as QML properties. This is the only file where
# Nix values cross into QML.
{
  pkgs,
  lib,
  colors,
  fontName,
  fontSize,
}:
pkgs.writeText "NixFFI.qml" ''
  // Build-time configuration generated by ffi.nix.
  import QtQuick

  QtObject {
      readonly property string fontFamily: "${fontName}"
      readonly property int    fontSize:   ${toString fontSize}

      readonly property QtObject color: QtObject {
          readonly property string base00: "#${colors.base00}"
          readonly property string base01: "#${colors.base01}"
          readonly property string base02: "#${colors.base02}"
          readonly property string base03: "#${colors.base03}"
          readonly property string base04: "#${colors.base04}"
          readonly property string base05: "#${colors.base05}"
          readonly property string base06: "#${colors.base06}"
          readonly property string base07: "#${colors.base07}"
          readonly property string base08: "#${colors.base08}"
          readonly property string base09: "#${colors.base09}"
          readonly property string base0A: "#${colors.base0A}"
          readonly property string base0B: "#${colors.base0B}"
          readonly property string base0C: "#${colors.base0C}"
          readonly property string base0D: "#${colors.base0D}"
          readonly property string base0E: "#${colors.base0E}"
          readonly property string base0F: "#${colors.base0F}"
      }

      readonly property QtObject bin: QtObject {
          readonly property string bash:     "${lib.getExe' pkgs.bash "bash"}"
          readonly property string cliphist: "${lib.getExe pkgs.cliphist}"
          readonly property string hyprctl:  "${lib.getExe' pkgs.hyprland "hyprctl"}"
          readonly property string jq:       "${lib.getExe pkgs.jq}"
          readonly property string kitty:    "${lib.getExe pkgs.kitty}"
          readonly property string stat:     "${lib.getExe' pkgs.coreutils "stat"}"
          readonly property string wlCopy:   "${lib.getExe' pkgs.wl-clipboard "wl-copy"}"
      }
  }
''
